const fs = require('fs');
let content = fs.readFileSync('src/utils/pdfGenerator.ts', 'utf8');

const replacements = {
  'PRONTURIO': 'PRONTUÁRIO',
  'pronturio': 'prontuário',
  'no': 'não',
  'est': 'está',
  'Emisso': 'Emissão',
  'clnico': 'clínico',
  'CLNICO': 'CLÍNICO',
  'FORA': 'FORÇA',
  'fora': 'força',
  'Razo': 'Razão',
  'razo': 'razão',
  'Equilbrio': 'Equilíbrio',
  'Advertncias': 'Advertências',
  'Propores': 'Proporções',
  'propores': 'proporções',
  'biomecnicas': 'biomecânicas',
  'trs': 'três',
  'PRESTAO': 'PRESTAÇÃO',
  'SERVIOS': 'SERVIÇOS',
  'Bancrio': 'Bancário',
  'Carto': 'Cartão',
  'Crdito': 'Crédito',
  'crdito': 'crédito',
  'Dbito': 'Débito',
  'maro': 'março',
  'n ': 'nº ',
  'Prestao': 'Prestação',
  'servios': 'serviços',
  'fsicas': 'físicas',
  'crditos': 'créditos',
  'clusula': 'cláusula',
  'Sesses': 'Sessões',
  'fisioterpico': 'fisioterápico',
  'emergncia': 'emergência',
  'teraputica': 'terapêutica',
  'ms': 'mês',
  'Avaliaes': 'Avaliações',
  'vigncia': 'vigência',
  'OBRIGAES': 'OBRIGAÇÕES',
  'disponibilizar': 'disponibilizará',
  'espao': 'espaço',
  'prestao': 'prestação',
  'comparecer': 'comparecerá',
  'horrios': 'horários',
  'antecedncia': 'antecedência',
  'implicaro': 'implicarão',
  'Resciso': 'Rescisão',
  'prvio': 'prévio',
  'VIGNCIA': 'VIGÊNCIA',
  'renovvel': 'renovável',
  'brao': 'braço',
  'antebrao': 'antebraço',
  'avaliao': 'avaliação',
  'Avaliao': 'Avaliação',
  'corao': 'coração',
  'leso': 'lesão',
  'LESO': 'LESÃO',
  'Mxima': 'Máxima',
  'mxima': 'máxima',
  'Mtrica': 'Métrica',
  'Referncia': 'Referência',
  'Mquina': 'Máquina',
  'Rotao': 'Rotação',
  'Abduo': 'Abdução',
  '  ': '⚠️ ',
  'portugus': 'português'
};

for (const [bad, good] of Object.entries(replacements)) {
  content = content.split(bad).join(good);
}

fs.writeFileSync('src/utils/pdfGenerator.ts', content, 'utf8');
console.log('Fixed replacements in pdfGenerator.ts');
